apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-server
  namespace: webhook
  labels:
    app: webhook-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-server
  template:
    metadata:
      labels:
        app: webhook-server
    spec:
      nodeName: cn-shanghai.192.168.37.225
      securityContext:
        runAsNonRoot: true
        runAsUser: 1234
      imagePullSecrets:
      - name: ali-hb-test.huifutest.com
      containers:
      - name: server
        image: ali-hb-test.huifutest.com/app/webhook-server:v1.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        ports:
        - containerPort: 8443
          name: webhook-api
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-server
  namespace: webhook
spec:
  selector:
    app: webhook-server
  ports:
    - port: 443
      targetPort: webhook-api
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: webhook
webhooks:
  - name: webhook-server.webhook.svc
    clientConfig:
      service:
        name: webhook-server
        namespace: webhook
        path: "/mutate"
      caBundle: ${CA_PEM_B64}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
