# A pod with a securityContext explicitly allowing it to run as root.
# The effect of deploying this with and without the webhook is the same. The
# explicit setting however prevents the webhook from applying more secure
# defaults.
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-override
  namespace: webhook
  labels:
    app: pod-with-override
spec:
  restartPolicy: OnFailure
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "36000"]
      resources:
          limits:
            memory: 600Mi
            cpu: 1200m
          requests:
            memory: 300Mi
            cpu: 500m
