# A pod with no securityContext specified.
# Without the webhook, it would run as user root (0). The webhook mutates it
# to run as the non-root user with uid 1234.
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-defaults
  namespace: webhook
  labels:
    app: pod-with-defaults
    oversale: enable
spec:
  restartPolicy: OnFailure
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600000"]
      resources:
        limits:
          cpu: "900m"
        requests:
          cpu: "300m"
